baseURL: https://The57thPick.com/
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

title: The57thPick.com
paginate: 5
theme: github.com/adityatelange/hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: The57thPick.com

  description: |
    A collection of interactive, data-driven, and reproducible essays.
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  cover:
    responsiveImages: false
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/fav/favicon.ico"
    favicon16x16: "/fav/favicon-16x16.png"
    favicon32x32: "/fav/favicon-32x32.png"
    apple_touch_icon: "/fav/apple-touch-icon.png"
    safari_pinned_tab: "/fav/safari-pinned-tab.svg"

  label:
    text: The57thPick.com
    # icon: "/img/logo.png"
    # iconHeight: 50

  profileMode:
    enabled: true
    title: The57thPick.com
    subtitle: "**Sports**, **media**, and **finance** --- *by the numbers*."
    imageUrl: "/img/logo.png" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Metrics
        url: /archive
      - name: Datasets
        url: "https://github.com/"
      - name: Archive
        url: /posts

  socialIcons:
    - name: twitter
      url: "https://twitter.com/jdkato"
    - name: rss
      url: "/index.xml"
    - name: github
      url: "https://github.com/jdkato"

    # - name: medium
    #   url: "https://medium.com/@jdkato"
    # - name: dev
    #   url: "https://dev.to/jdkato"

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: github
      name: GitHub
      url: https://github.com/The57thPick
      weight: 30

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

  goldmark:
    renderer:
      unsafe: true
